# Generated by Django 4.0.6 on 2022-08-22 22:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_imovel', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 22, 50, 36, 530874, tzinfo=utc))),
                ('bairro_imovel', models.CharField(max_length=65)),
                ('rua_imovel', models.CharField(max_length=100)),
                ('numero_imovel', models.IntegerField()),
                ('telefone_imovel', models.IntegerField()),
                ('tamanho_imovel', models.IntegerField()),
                ('qtd_quartos_imovel', models.ImageField(upload_to='')),
                ('qtd_banheiros_imovel', models.IntegerField()),
                ('garagem_imovel', models.BinaryField()),
                ('pets_imovel', models.BinaryField()),
                ('venda_alugel_imovel', models.BinaryField()),
                ('informacao_imovel', models.TextField()),
                ('imagens_imovel', models.ImageField(blank=True, null=True, upload_to='imovel_img/%Y/%m/%d')),
                ('publicado_imovel', models.BooleanField(default=False)),
                ('anunciante_imovel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('categoria_imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.categoria')),
            ],
        ),
    ]
