# Generated by Django 4.0.6 on 2022-09-14 12:31

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='preco_imovel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='quintal_imovel',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='', max_length=3, verbose_name='quintal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='anunciante_imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='anunciante'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='bairro_imovel',
            field=models.CharField(max_length=65, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='categoria_imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.categoria', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='data_imovel',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 12, 31, 34, 575129, tzinfo=utc), verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='garagem_imovel',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='garagem'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='numero_imovel',
            field=models.IntegerField(verbose_name='número imovel'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='pets_imovel',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='pets'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='qtd_quartos_imovel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='rua_imovel',
            field=models.CharField(max_length=100, verbose_name='rua'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='telefone_imovel',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='error.', regex='(\\(?\\d{2}\\)?\\s)?(\\d{4,5}\\-\\d{4})')]),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='venda_alugel_imovel',
            field=models.CharField(choices=[('Venda', 'Venda'), ('Aluguel', 'Aluguel')], max_length=7, verbose_name='venda ou aluguel'),
        ),
    ]
