# Generated by Django 4.0.6 on 2022-09-14 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_imovel_preco_imovel_imovel_quintal_imovel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='av_rua_imovel',
            field=models.CharField(choices=[('Rua', 'Rua'), ('Avenida', 'Avenida')], default='', max_length=7, verbose_name='av ou rua'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='data_imovel',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 13, 6, 16, 430278, tzinfo=utc), verbose_name='data'),
        ),
    ]
