# Generated by Django 4.0.6 on 2022-09-23 00:32

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imoveis', '0003_imovel_av_rua_imovel_alter_imovel_data_imovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='favoritos',
            field=models.ManyToManyField(blank=True, default=None, related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='data_imovel',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 0, 32, 21, 630745, tzinfo=utc), verbose_name='data'),
        ),
    ]
